// flow-typed signature: c1c8eff6682916a03ef0907763ad8a5b
// flow-typed version: <<STUB>>/hdkey_v1.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hdkey'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hdkey' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hdkey/lib/hdkey' {
  declare module.exports: any;
}

declare module 'hdkey/test/hdkey.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hdkey/lib/hdkey.js' {
  declare module.exports: $Exports<'hdkey/lib/hdkey'>;
}
declare module 'hdkey/test/hdkey.test.js' {
  declare module.exports: $Exports<'hdkey/test/hdkey.test'>;
}
