// flow-typed signature: 2eef3f8267f4efabcf0a6835644c32fc
// flow-typed version: <<STUB>>/@ledgerhq/hw-app-eth_v4.19.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-app-eth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-app-eth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-app-eth/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/lib/Eth' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/lib/utils' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/src/Eth' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-app-eth/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-app-eth/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-eth/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-app-eth/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@ledgerhq/hw-app-eth/lib/Eth.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/lib/Eth'>;
}
declare module '@ledgerhq/hw-app-eth/lib/utils.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/lib/utils'>;
}
declare module '@ledgerhq/hw-app-eth/src/Eth.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/src/Eth'>;
}
declare module '@ledgerhq/hw-app-eth/src/utils.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-app-eth/src/utils'>;
}
