// flow-typed signature: d62eb8d7f96c499eb01ea1a480ff5d62
// flow-typed version: <<STUB>>/@ledgerhq/hw-transport-u2f_v4.20.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-transport-u2f'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-transport-u2f' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-transport-u2f/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-u2f/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-u2f/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-u2f/flow-typed/npm/u2f-api_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-u2f/lib/TransportU2F' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport-u2f/src/TransportU2F' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-transport-u2f/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-u2f/flow-typed/npm/@ledgerhq/hw-transport_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-u2f/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-u2f/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-transport-u2f/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-u2f/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport-u2f/flow-typed/npm/u2f-api_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-u2f/flow-typed/npm/u2f-api_v0.x.x'>;
}
declare module '@ledgerhq/hw-transport-u2f/lib/TransportU2F.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-u2f/lib/TransportU2F'>;
}
declare module '@ledgerhq/hw-transport-u2f/src/TransportU2F.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport-u2f/src/TransportU2F'>;
}
