// flow-typed signature: 0a98f7a9c893111236992102b6fcc80b
// flow-typed version: <<STUB>>/@ledgerhq/hw-transport_v4.19.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@ledgerhq/hw-transport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@ledgerhq/hw-transport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@ledgerhq/hw-transport/flow-typed/npm/events_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport/lib/Transport' {
  declare module.exports: any;
}

declare module '@ledgerhq/hw-transport/src/Transport' {
  declare module.exports: any;
}

// Filename aliases
declare module '@ledgerhq/hw-transport/flow-typed/npm/events_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/flow-typed/npm/events_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@ledgerhq/hw-transport/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module '@ledgerhq/hw-transport/lib/Transport.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/lib/Transport'>;
}
declare module '@ledgerhq/hw-transport/src/Transport.js' {
  declare module.exports: $Exports<'@ledgerhq/hw-transport/src/Transport'>;
}
